// This is config_debug.h
//
// This file contains the debug configuration options.
// This file was generated by configure_1.sh
//
// $Id$

// Define to 1 if you want to show the cycle counter
#define HIDE_COUNTER 1

// Define to 1 if you want to show estimate speed
#undef MIPS_ESTIMATE

// Define to 1 if you want to show memory map
#undef DUMP_MEMMAP

// Define to 1 if you want to check for overlapping of memory ranges
//#define CHECK_MEM_RANGES 1

// Define if you want to enable VGA debugging
//#define DEBUG_VGA
//#define DEBUG_VGA_NOISY

// Define if you want to enable a large amount of VGA mem_w output
//#define DEBUG_VGA_MEMW

// Define to 1 if you want to enable Serial Port debugging
#undef DEBUG_SERIAL

// Define to 1 if you want to enable IDE General debugging
#undef DEBUG_IDE

// Define to 1 if you want to enable IDE Busmaster debugging
#undef DEBUG_IDE_BUSMASTER

// Define to 1 if you want to enable IDE Command debugging
#undef DEBUG_IDE_COMMAND

// Define to 1 if you want to enable IDE CMD debugging
#undef DEBUG_IDE_CMD

// Define to 1 if you want to enable IDE DMA debugging
#undef DEBUG_IDE_DMA

// Define to 1 if you want to enable IDE Interrupt debugging
#undef DEBUG_IDE_INTERRUPT

// Define to 1 if you want to enable IDE Command Register debugging
#undef DEBUG_IDE_REG_COMMAND

// Define to 1 if you want to enable IDE Control Register debugging
#undef DEBUG_IDE_REG_CONTROL

// Define to 1 if you want to enable IDE ATAPI Packet debugging
#undef DEBUG_IDE_PACKET

// Define to 1 if you want to enable IDE Thread debugging
#undef DEBUG_IDE_THREADS

// Define to 1 if you want to enable IDE Mutexes debugging
#undef DEBUG_IDE_LOCKS

// Define to 1 if you want to enable IDE Multiple debugging
#undef DEBUG_IDE_MULTIPLE

// Define to 1 if you want to enable Floating Point conversions debugging
#undef DEBUG_FP_CONVERSION

// Define to 1 if you want to enable Floating Point load/store debugging
#undef DEBUG_FP_LOADSTORE

// Define to 1 if you want to enable General NIC debugging
#undef DEBUG_NIC

// Define to 1 if you want to enable NIC Filter debugging
#undef DEBUG_NIC_FILTER

// Define to 1 if you want to enable NIC Serial ROM debugging
#undef DEBUG_NIC_SROM

// Define if you want to enable unknown memory access debugging
//#define DEBUG_UNKMEM

// Define to 1 if you want to enable PCI debugging
#undef DEBUG_PCI

// Define to 1 if you want to enable Translationbuffer debugging
#undef DEBUG_TB

// Define if you want to enable I/O Port Access debugging
//#define DEBUG_PORTACCESS

// Define if you want to enable Keyboard debugging
//#define DEBUG_KBD

// Define if you want EXTRA keyboard debugging
//#define DEBUG_KBD_NOISY

// Define to 1 if you want to enable Programmable Interrupt Controller (PIC) debugging
#undef DEBUG_PIC

// Define to 1 if you want to enable Printer port debugging
#undef DEBUG_LPT

// Define to 1 if you want to enable USB Controller debugging
#undef DEBUG_USB

// Define if you want to enable SCSI Device debugging
//#define DEBUG_SCSI

// Define if you want to enable Symbios SCSI Controller debugging
// apparently this only used to set the following two items.... wut
//#define DEBUG_SYM

// Define if you want to enable Symbios Registers debugging
//#define DEBUG_SYM_REGS

// Define if you want to enable Symbios SCRIPTS Execution debugging
//#define DEBUG_SYM_SCRIPTS

// Define to 1 if you want to enable DMA Controller debugging
#undef DEBUG_DMA

// Define to 1 if you want to enable backtrace on SIGSEGV debugging
#undef DEBUG_BACKTRACE

// Define to 1 if you want to enable mutex debugging
#undef DEBUG_LOCKS

// Define to 1 if you want to enable SDL Key translation debugging
#undef DEBUG_SDL_KEY

// Define for specific firmware debug paths
//#define DEBUG_ARC
//#define DEBUG_PAL

//#define DEBUG_CCHIP

// Define for these VGA debugs
//#define DEBUG_VGA_EXITS
//#define DEBUG_VGA_UPDATES

// Define to dump CTB turboslot for fixup for BSDs
//#define DEBUG_HWRPB_TURBOSLOT

// Define if you want to enable unaligned access debugging
//#define DEBUG_UNALIGN

// Define if you want to enable SuperIO debugging
//#define DEBUG_SUPERIO

// Working on VGA rendering for graphical components
//#define DEBUG_VGA_RENDER

// Define if you want to enable S3 linear framebuffer tracing
//#define S3_LFB_TRACE 

// Comment out to disable bypassing SRM memory checks (doesn't work well down near SRM 7.0 ranges)
#define SKIP_SRM_MEMTEST
