/* ES40 emulator.
 * Copyright (C) 2007-2008 by the ES40 Emulator Project
 *
 * WWW    : https://github.com/gdwnldsKSC/es40
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * 
 * Although this is not required, the author would appreciate being notified of, 
 * and receiving any modifications you may make to the source code that might serve
 * the general public.
 *
 * Parts of this file based upon the Poco C++ Libraries, which is Copyright (C) 
 * 2004-2006, Applied Informatics Software Engineering GmbH. and Contributors.
 */

//
// Mutex.h
//
// $Id$
//
// Library: Foundation
// Package: Threading
// Module:  Mutex
//
// Definition of the Mutex and FastMutex classes.
//
// Copyright (c) 2004-2008, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#ifndef Foundation_Mutex_INCLUDED
#define Foundation_Mutex_INCLUDED

#include <mutex>
#include <chrono>
#include <cstdio>
#include <string>

#include "ScopedLock.h"
#include "Exception.h"
#include "../es40_debug.h"

#if defined(NO_LOCK_TIMEOUTS)
#if !defined(LOCK_TIMEOUT_MS)
#define LOCK_TIMEOUT_MS
#endif
#else
#if !defined(LOCK_TIMEOUT_MS)
#define LOCK_TIMEOUT_MS 5000
#endif
#endif

extern thread_local const char* tl_threadName;

#define CURRENT_THREAD_NAME (tl_threadName ? tl_threadName : "main")

class CMutex
{
public:
  typedef CScopedLock<CMutex> CScopedLock;

  CMutex() : lockName(const_cast<char*>("?")) {}

  explicit CMutex(const char* lName)
    : lockName(const_cast<char*>(lName)) {
  }

  ~CMutex() = default;

  void lock()
  {
#if defined(DEBUG_LOCKS)
    printf("        LOCK mutex %s from thread %s.\n", lockName, CURRENT_THREAD_NAME);
#endif
    _mutex.lock();
#if defined(DEBUG_LOCKS)
    printf("      LOCKED mutex %s from thread %s.\n", lockName, CURRENT_THREAD_NAME);
#endif
  }

  void lock(long milliseconds)
  {
#if defined(DEBUG_LOCKS)
    printf("        LOCK mutex %s from thread %s.\n", lockName, CURRENT_THREAD_NAME);
#endif
    if (!_mutex.try_lock_for(std::chrono::milliseconds(milliseconds)))
    {
      printf("TIMEOUT locking mutex %s from thread %s after %ld ms.\n",
        lockName, CURRENT_THREAD_NAME, milliseconds);
      throw std::runtime_error("Mutex lock timeout");
    }
#if defined(DEBUG_LOCKS)
    printf("      LOCKED mutex %s from thread %s.\n", lockName, CURRENT_THREAD_NAME);
#endif
  }

  bool tryLock()
  {
    bool res = _mutex.try_lock();
#if defined(DEBUG_LOCKS)
    printf("  %s mutex %s from thread %s.\n",
      res ? "    LOCKED" : "CAN'T LOCK", lockName, CURRENT_THREAD_NAME);
#endif
    return res;
  }

  bool tryLock(long milliseconds)
  {
    bool res = _mutex.try_lock_for(std::chrono::milliseconds(milliseconds));
#if defined(DEBUG_LOCKS)
    printf("  %s mutex %s from thread %s.\n",
      res ? "    LOCKED" : "CAN'T LOCK", lockName, CURRENT_THREAD_NAME);
#endif
    return res;
  }

  void unlock()
  {
#if defined(DEBUG_LOCKS)
    printf("      UNLOCK mutex %s from thread %s.\n", lockName, CURRENT_THREAD_NAME);
#endif
    _mutex.unlock();
  }

  char* lockName;

private:
  std::recursive_timed_mutex _mutex;

  CMutex(const CMutex&) = delete;
  CMutex& operator=(const CMutex&) = delete;
};

class CFastMutex
{
public:
  typedef CScopedLock<CFastMutex> CScopedLock;

  CFastMutex() : lockName(const_cast<char*>("?")) {}

  explicit CFastMutex(const char* lName)
    : lockName(const_cast<char*>(lName)) {
  }

  ~CFastMutex() = default;

  void lock()
  {
#if defined(DEBUG_LOCKS)
    printf("        LOCK fast-mutex %s from thread %s.\n", lockName, CURRENT_THREAD_NAME);
#endif
    _mutex.lock();
#if defined(DEBUG_LOCKS)
    printf("      LOCKED fast-mutex %s from thread %s.\n", lockName, CURRENT_THREAD_NAME);
#endif
  }

  void lock(long milliseconds)
  {
#if defined(DEBUG_LOCKS)
    printf("        LOCK fast-mutex %s from thread %s.\n", lockName, CURRENT_THREAD_NAME);
#endif
    if (!_mutex.try_lock_for(std::chrono::milliseconds(milliseconds)))
    {
      printf("TIMEOUT locking fast-mutex %s from thread %s after %ld ms.\n",
        lockName, CURRENT_THREAD_NAME, milliseconds);
      throw std::runtime_error("FastMutex lock timeout");
    }
#if defined(DEBUG_LOCKS)
    printf("      LOCKED fast-mutex %s from thread %s.\n", lockName, CURRENT_THREAD_NAME);
#endif
  }

  bool tryLock()
  {
    bool res = _mutex.try_lock();
#if defined(DEBUG_LOCKS)
    printf("  %s fast-mutex %s from thread %s.\n",
      res ? "    LOCKED" : "CAN'T LOCK", lockName, CURRENT_THREAD_NAME);
#endif
    return res;
  }

  bool tryLock(long milliseconds)
  {
    bool res = _mutex.try_lock_for(std::chrono::milliseconds(milliseconds));
#if defined(DEBUG_LOCKS)
    printf("  %s fast-mutex %s from thread %s.\n",
      res ? "    LOCKED" : "CAN'T LOCK", lockName, CURRENT_THREAD_NAME);
#endif
    return res;
  }

  void unlock()
  {
#if defined(DEBUG_LOCKS)
    printf("      UNLOCK fast-mutex %s from thread %s.\n", lockName, CURRENT_THREAD_NAME);
#endif
    _mutex.unlock();
  }

  char* lockName;

private:
  std::timed_mutex _mutex;

  CFastMutex(const CFastMutex&) = delete;
  CFastMutex& operator=(const CFastMutex&) = delete;
};

#define MUTEX_LOCK(mutex)         (mutex)->lock(LOCK_TIMEOUT_MS)
#define MUTEX_READ_LOCK(mutex)    (mutex)->readLock(LOCK_TIMEOUT_MS)
#define MUTEX_WRITE_LOCK(mutex)   (mutex)->writeLock(LOCK_TIMEOUT_MS)
#define MUTEX_UNLOCK(mutex)       (mutex)->unlock()
#define SCOPED_M_LOCK(mutex)      CMutex::CScopedLock   L_##__LINE__(mutex)
#define SCOPED_FM_LOCK(mutex)     CFastMutex::CScopedLock L_##__LINE__(mutex)

#endif // Foundation_Mutex_INCLUDED
